### ISSUE TITLE
Resolve FIXME

### ISSUE THREAD

**Issue by xphoenix** [siongui/go-succinct-data-structure-trie#1]
func (bw *BitWriter) Write(data, numBits uint) {
	//for i := (numBits-1); i >= 0; i-- {
	//FIXME: the above commented line will cause infinite loop, why???
	for i := numBits; i > 0; i-- {

Because I becomes uint, lets check iteration when i == 0, at the end of loop, i-- takes place but as I is uint, it leans to 2^32-1 instead of -1, loop condition is still true...

**Comment by siongui** [comment]
Thank you!!! Now I understand!!!
