### ISSUE TITLE
Insert of the same word twice adds 2 entries

### ISSUE THREAD

**Issue by achandak123** [siongui/go-succinct-data-structure-trie#2]

**Comment by siongui** [comment]
Thanks for reporting the bug. This may not be fixed soon because I already forget the details of the code.

**Comment by siongui** [comment]
Cannot re-produce the issue in my testing. Please give sample code for producing the issue and re-open this issue. Thanks

**Comment by achandak123** [comment]
not an issue, it was mistake in my code, thanks for checking it out
